// Natural Earth 1:10m land and country borders, 0 to 15 longitude, -60 to -45 latitude (public domain). Generated by scripts/generate-world-map-data.ts; do not edit.
export const STEP = 0.001;
export const LAND = "awEjfiB{@Vd@lAr@LtB@b@XZKHiA}@w@yAU";
export const BORDERS = "";
