// Natural Earth 1:10m land and country borders, 15 to 30 longitude, 15 to 30 latitude (public domain). Generated by scripts/generate-world-map-data.ts; do not edit.
export const STEP = 0.001;
export const LAND = "iry@iry@?bi\\bi\\??ci\\";
export const BORDERS = "yym@oae@vrNyuF af^ixl@f@Dr{@lZ eh\\a`_@q[u\\[e@Kk@oOuyD}@{CuKcUBa@Zk@xPqQ`DyBb@e@r@}ANyAO{Aq@mAoAk@fRc[bAoAdCeA\\]H_@Nk]`Jwx@ ixo@u}i@?p{BFJP@hE? eqo@u`f@hl@? {cn@u`f@`I??d^ iym@us]U{@D}jF qam@iw]eF?qFb@iFlAu@@ qpl@as]uCMeG}AcC[ }fl@au]sH~@ cmk@eh\\uCyCg@_@qBq@MQyA_DOk@WgFBcAR}@rAeB`@q@Ly@M}@e@m@}C}A}BwCu@a@oCQ mjo@iry@iBbFGl@@d@`@hBMpAeBvC]pAP~DClASdAeD|Ia@jBMrB?b`M ixo@u}i@_yH?";
