// Natural Earth 1:10m land and country borders, 30 to 45 longitude, -60 to -45 latitude (public domain). Generated by scripts/generate-world-map-data.ts; do not edit.
export const STEP = 0.001;
export const LAND = "{phAxmzAaAMcADwDd@}AjAw@NTr@h@p@v@b@z@Lp@MzFAfAG`@Id@c@Nw@e@U i}hAvazAGk@eA[{AC_Ab@Bx@hAP~AG";
export const BORDERS = "";
