// Natural Earth 1:10m land and country borders, 30 to 45 longitude, -45 to -30 latitude (public domain). Generated by scripts/generate-world-map-data.ts; do not edit.
export const STEP = 0.001;
export const LAND = "im{@tqy@x@l@x@~@~ApCpBbF~G|L~@jC~AvArI`Pv@dA^\\v@\\|@tBjI|Jv@`@~@vBhBhB\\V?ypA";
export const BORDERS = "";
