// Natural Earth 1:10m land and country borders, 30 to 45 longitude, 75 to 90 latitude (public domain). Generated by scripts/generate-world-map-data.ts; do not edit.
export const STEP = 0.001;
export const LAND = "us_Agu{CoKg@iTt@vAb@hBN|^n@pKjAfkAvBjG}@GM]IgyAsDoBY{CA kvy@_iyC}M?w@Zr@NfAHfC@YLfAJ~ACvAY cnfA}p{CuB_@qKl@x@RlABvGIx@I y{vAol|CxEIlAWcBYcEG";
export const BORDERS = "";
