// Natural Earth 1:10m land and country borders, 45 to 60 longitude, -60 to -45 latitude (public domain). Generated by scripts/generate-world-map-data.ts; do not edit.
export const STEP = 0.001;
export const LAND = "__aB`~xA[O{CYq@~@If@Jf@ZT`@?vB[\\SN_@ sfdBpqyAe@Z]d@xApAdBKZJx@Gl@QfAcAXs@S[iCiAo@Bc@ZOl@MJ";
export const BORDERS = "";
