// Natural Earth 1:10m land and country borders, 60 to 75 longitude, -15 to 0 latitude (public domain). Generated by scripts/generate-world-map-data.ts; do not edit.
export const STEP = 0.001;
export const LAND = "gplCnlMWe@ITF\\~ApAJw@KqBLo@|As@h@y@YB{BzAKn@JhD gqlCzeMUb@h@vAIj@Ti@e@mARo@f@m@`@w@SL kjjCx~KW?LD ydjChnK?UKOAX sijCfbKQ[[IRl@JH ydkC~rITOS@ qbkChiIS]BP _dkChfIQEDH {pkCdfIDOE? u{mCri@SLLA g~mC|h@XVGQ gymC~g@ERDA o`nCbf@X`@Eg@IG }`nCxc@Bb@P]EOOK ulnCvPOPCTRS swmCnd@[`@Mn@N?^gAFe@[M?NJ?";
export const BORDERS = "";
