// Natural Earth 1:10m land and country borders, 60 to 75 longitude, -30 to -15 latitude (public domain). Generated by scripts/generate-world-map-data.ts; do not edit.
export const STEP = 0.001;
export const LAND = "g~zBzle@c@FFd@h@j@fBXdB|@bA}@Ec@OO{Aq@_AUaAG";
export const BORDERS = "";
