// Natural Earth 1:10m land and country borders, 75 to 90 longitude, -45 to -30 latitude (public domain). Generated by scripts/generate-world-map-data.ts; do not edit.
export const STEP = 0.001;
export const LAND = "_kvC|zhAoAE}@n@Sz@f@d@v@N~@e@`@{@ ylvChrjA_@j@FJx@CPk@GMOG";
export const BORDERS = "";
