// Natural Earth 1:10m land and country borders, 90 to 105 longitude, 30 to 45 latitude (public domain). Generated by scripts/generate-world-map-data.ts; do not edit.
export const STEP = 0.001;
export const LAND = "uwnDuqy@?ci\\ci\\??bi\\";
export const BORDERS = "}qtDy{vAN? susDy{vA|AN ursDi{vA^Ax@M iduDgzvAp@CjCm@ axtDy{vAh@B wvtDu{vARC artDy{vAB? uuvDuevAfDQ~AYfBqA`IaIr@_@dIwBnEG~C{@n@A iguDszvA~AJ {hwDo|uAv@O^_@t@uAb@e@bD_Cz@W^A i{vDufvAxA\\xA@ yrxD}luAtAGnDeA~KaBpA{AhC}AzHgC {lwDo|uA~B? uf{DamrAh@ELa@ZyFJo@Vg@p@m@bWsPbA_Ad@kAj@wFxG{LlE{MjBqDp@i@dAOfBC|Dc@PS?o@QqBHwBc@{@Ku@sA{AQg@d@K ehyD}nuAjT~@ chaEgcrApmC}L qy|DeqrAzk@lB~DT eudEcarAbjAeH ajbEijrAxA@b^~E _khEs_qA|@U|_AgJvBm@nDkClHmJ`EkB`Fk@bFO eaeEabrA~J\\ yalEsfpA|@N qqiEwppAz@Etc@uM {_lEcfpAvBgBj@MdQ?~DWLQEyK ibkE}wpAvo@dF";
