// Natural Earth 1:10m land and country borders, 90 to 105 longitude, 60 to 75 latitude (public domain). Generated by scripts/generate-world-map-data.ts; do not edit.
export const STEP = 0.001;
export const LAND = "uwnDudtB?ci\\ci\\??bi\\";
export const BORDERS = "";
