// Natural Earth 1:10m land and country borders, 135 to 150 longitude, 0 to 15 latitude (public domain). Generated by scripts/generate-world-map-data.ts; do not edit.
export const STEP = 0.001;
export const LAND = "_|lGouQR`@C\\[Hi@S`@v@n@h@ZILi@XHvCxEFo@QcA_@}@o@g@YyA]OKLEr@Ig@Q]i@YQ? k~yGosYUj@a@XkAJ?VxAjCdA~@~BlAp@r@ZpAPxDn@hAb@Lf@@`@Kt@oARyAb@Ya@i@G{@Vw@TMWWIHYAaG{Cw@iAw@}Cw@g@[A gsbHqaLAYKQCV ckbHwkMHQM@ iicH}vOFYE_@OWU?CP cmqGoaROMQACFb@T krzGiuZ{Ae@w@EUj@Pf@~@Th@z@d@Pf@Ub@GzADLMWa@s@a@ on{Gyh\\QVERLr@\\t@f@\\f@YNqAf@gA {axGujM@IEHHT ykbH_kMEKGJRZDK cjbHykMQ@QNDH^M u|wGokMGQI?@J _~wG{kMCGAJ {axGykMBJNGCO";
export const BORDERS = "";
