// Natural Earth 1:10m land and country borders, 150 to 165 longitude, 0 to 15 latitude (public domain). Generated by scripts/generate-world-map-data.ts; do not edit.
export const STEP = 0.001;
export const LAND = "edtHspLIRQFg@MYfBARdAD[pAF^PRXF~ALd@ARWh@NZQf@s@Ks@DWRSM[t@CL]KcASSgAIEm@u@ZSKo@JeA?g@XKP wjlH}}NSNEx@Hd@VX`@g@pAa@W{@SM}@I ojmH_y@SJHFT?DK udmHk{@MEUBJJV? qimHw{@GJHDNAJI?IKA }nmHoiFB_@]UC^ iimH_lFE\\b@TD] gckHkiIGWYW_@MSBDR s}qH{gJFIK? _nsHybLESSIDP argHihMBiBONET@V mwdH_wOBSG@ kedH_pPKSQ?BH cl}HylIc@RELFXn@jAXDp@ObBG\\IFa@Wa@eCkBg@I]T iagHolMaAO[H[b@A\\Jb@TNT]L?PLlAMm@Ss@KKMHSh@D isgHeqMMIcAHt@n@d@N^BAk@Ke@ _lyHqaRYBCFx@I aa|HadUc@SFNb@R aa|HcuUBFZQSC k{{H_xUIIKX";
export const BORDERS = "";
