// Natural Earth 1:10m land and country borders, 150 to 165 longitude, 15 to 30 latitude (public domain). Generated by scripts/generate-world-map-data.ts; do not edit.
export const STEP = 0.001;
export const LAND = "ivkHcmn@OIIFBNVC {ukHinn@X^Vc@YI";
export const BORDERS = "";
