// Natural Earth 1:10m land and country borders, 150 to 165 longitude, 75 to 90 latitude (public domain). Generated by scripts/generate-world-map-data.ts; do not edit.
export const STEP = 0.001;
export const LAND = "i~pHgruCWXBLb@FpGGn@S][uA[mA? uqiHmvsCUJITLb@tBt@fBJhCUnF_Ax@Y]YcBa@sDc@mFQaBHZp@ wqeHuxqC_A@eCR}@R~ABdBZ|Al@~@x@ML`@Z`Ch@DZb@Az@TNJGL|g@??wMkGH{AXi@Te@\\@RdBf@cBUiBBmH|@_HJj@R|APh@Py@LeACcEi@u@]ISAYOIgAM";
export const BORDERS = "";
