// Natural Earth 1:10m land and country borders, 150 to 165 longitude, -60 to -45 latitude (public domain). Generated by scripts/generate-world-map-data.ts; do not edit.
export const STEP = 0.001;
export const LAND = "yiuH|miB]]oAS[a@JbDz@`CRdAl@fAJd@@t@HX\\Fv@?JWKOJc@[qBYi@Ji@e@u@Qg@";
export const BORDERS = "";
