// Natural Earth 1:10m land and country borders, 165 to 180 longitude, 15 to 30 latitude (public domain). Generated by scripts/generate-world-map-data.ts; do not edit.
export const STEP = 0.001;
export const LAND = "uldIctd@e@GEOJWYNGZNN";
export const BORDERS = "";
