// Natural Earth 1:10m land and country borders, -15 to 0 longitude, -30 to -15 latitude (public domain). Generated by scripts/generate-world-map-data.ts; do not edit.
export const STEP = 0.001;
export const LAND = "rdJha^sACYI]`ACZF\\P^lAp@Z[ZZ^Pb@B^ORYg@cB]]";
export const BORDERS = "";
