// Natural Earth 1:10m land and country borders, -15 to 0 longitude, -45 to -30 latitude (public domain). Generated by scripts/generate-world-map-data.ts; do not edit.
export const STEP = 0.001;
export const LAND = "jkRxxmAg@\\Uj@z@VnA]rCwA?MQc@OMuBIYBMN d`WzkgA][}ADkB~@PXxAbAd@TX?rByA";
export const BORDERS = "";
