// Natural Earth 1:10m land and country borders, -15 to 0 longitude, 75 to 90 latitude (public domain). Generated by scripts/generate-world-map-data.ts; do not edit.
export const STEP = 0.001;
export const LAND = "xh\\kx~CybAB}t@~DsGMgFNyEj@wFE{`@tB}HlAwF~AiAbAs@VqNXoB\\d@\\dNpC|_@nBf@LnAz@d@LlAJhHpAtBLpATKd@@TRJvd@dEzBGhDx@`Af@f@h@XBrSd@rWe@r\\x@yBj@_QlBoCv@p@xAvAh@zDfAjSjAnEKnP`@";
export const BORDERS = "";
