// Natural Earth 1:10m land and country borders, -15 to 0 longitude, -15 to 0 latitude (public domain). Generated by scripts/generate-world-map-data.ts; do not edit.
export const STEP = 0.001;
export const LAND = "f`[xkNQ\\iAv@]`@lBz@pAH\\KVeAU]_@eA[UMT HF?QQ??P";
export const BORDERS = "";
