// Natural Earth 1:10m land and country borders, -30 to -15 longitude, -30 to -15 latitude (public domain). Generated by scripts/generate-world-map-data.ts; do not edit.
export const STEP = 0.001;
export const LAND = "rhx@neg@Rm@GSWB]^ dlw@lag@EOE@";
export const BORDERS = "";
