// Natural Earth 1:10m land and country borders, -30 to -15 longitude, -60 to -45 latitude (public domain). Generated by scripts/generate-world-map-data.ts; do not edit.
export const STEP = 0.001;
export const LAND = "hft@bcsBEUMKWE{DA?LPPLb@xB@h@G `kt@xasBYz@]Hj@?~A_@v@WNW{@O{A@ j_s@zfrBeAG_AJ_Cp@zAn@n@Lt@DbAGn@a@Dk@ nrr@h|oBv@At@Qh@[X_@eAw@e@Mi@Li@bAy@L_A?^T |_t@fumBmARc@RCR\\PpBP~@IVKFYMSc@M r|t@f}lBa@]i@Gk@Dk@P?L\\Hr@n@ xes@dmnBg@Um@Dk@Tc@b@ZLLMV@ hbv@rwmBg@Sk@@CTb@Rl@A fhr@hcqBi@|@L|@DGfBc@`Gq@v@q@u@sA_@EmE?eAH}@^";
export const BORDERS = "";
