// Natural Earth 1:10m land and country borders, -45 to -30 longitude, 45 to 60 latitude (public domain). Generated by scripts/generate-world-map-data.ts; do not edit.
export const STEP = 0.001;
export const LAND = "|_vAietB|@^bA@`A]BCtB?PJ|@@f@IFC |ruAadtBb@d@z@Xt@ELy@Wg@tA?NBZABAyJ?@?Nj@PHVCNOJa@t@?HV rtsAietBl@Z]TRh@l@f@f@P^G\\m@ZHTRJZGVrALOMg@_BLMU[Mg@ jbvAwbtBS[{@Q{@?YP?j@v@TbAC jksAectBp@?l@LcAX`@N`AE\\JZTRk@@UPCLBNbARRXHZEsA_DYQqBR ~|tAietBNZvBdAbAV`A|@^RVSAYSkA@k@L@J\\?d@t@~AnBRz@ZxBFtBcAu@Q{B{AeAa@Uk@EC tjtA}~sB_Bf@e@ZH\\XDv@a@pAt@`@MLDF^fAXVUKYJOg@[]_@AWj@@b@Pb@^Rd@Ib@`@^n@Vr@Jj@EZ[C_@{@eBFWTOXp@`Bl@G\\bA^zAVrACj@s@Is@Oa@cA{@{EmC_BLaBh@cD^s@N fisAietBb@Pz@H`@ITQrN?h@ZFv@x@XFXNVr@Bn@If@WJMPoAj@UN?HJBdARHn@@dBIn@Kj@QdDi@d@Y";
export const BORDERS = "";
