// Natural Earth 1:10m land and country borders, -45 to -30 longitude, 30 to 45 latitude (public domain). Generated by scripts/generate-world-map-data.ts; do not edit.
export const STEP = 0.001;
export const LAND = "n}{@idlAk@VYBYMe@d@O`@AtALl@b@t@f@`@`@Qd@LrA?ZMPYLg@?c@QSHa@q@_Ca@UkAG xw{@_rlAcAHEz@f@x@~@Hh@sAESQS";
export const BORDERS = "";
