// Natural Earth 1:10m land and country borders, -60 to -45 longitude, 30 to 45 latitude (public domain). Generated by scripts/generate-world-map-data.ts; do not edit.
export const STEP = 0.001;
export const LAND = "bxsByztAmDaBbB~AdBr@bB^bBN`EB?o@M?{FGgBW";
export const BORDERS = "";
