// Natural Earth 1:10m land and country borders, -90 to -75 longitude, -30 to -15 latitude (public domain). Generated by scripts/generate-world-map-data.ts; do not edit.
export const STEP = 0.001;
export const LAND = "dnqCdh\\?bi\\?mk[TQZGx@FpBgBlB_@J]j@O?WcAWEY\\k@x@a@nAa@t@u@e@@UIISJi@nBkBf@QfBMZUb@oA|AcCLg@NSFE z`{Ctmr@UHAFd@B ~l{Crhr@KPb@?";
export const BORDERS = "";
