// Natural Earth 1:10m land and country borders, -90 to -75 longitude, -45 to -30 latitude (public domain). Generated by scripts/generate-world-map-data.ts; do not edit.
export const STEP = 0.001;
export const LAND = "lv|Cl}`Ab@aASaAs@_@{@f@Mx@@`ARJ`@B`@A h{xCps`AQFk@z@j@?f@NPMFLv@]l@Kh@DfA\\fAPj@VN?HWaBqAqA[Sm@MEiAHg@RWb@ dtqCvnvAw@dAqAXh@r@WbAf@Bb@Z^DzADh@IXMa@o@CWPYz@s@\\k@CSm@o@w@e@cADYR";
export const BORDERS = "";
