// Natural Earth 1:10m land and country borders, -105 to -90 longitude, 30 to 45 latitude (public domain). Generated by scripts/generate-world-map-data.ts; do not edit.
export const STEP = 0.001;
export const LAND = "xalEuqy@?ci\\ci\\??tu[Pa@lBiAfDq@zAK`ADl@Zl@h@|BxCrCnBl@|@HzAe@fAcAt@qAZqCJeAf@}B^m@?qAUeCIqAWAA?rB";
export const BORDERS = "|mkEuqy@VgADo@k@}CBuBZ]d@gAbAg@nAoCn@]H{@f@Y\\c@Au@\\cAOo@h@[LqA|AuB`BSJQL_APU";
