// Natural Earth 1:10m land and country borders, -105 to -90 longitude, 0 to 15 latitude (public domain). Generated by scripts/generate-world-map-data.ts; do not edit.
export const STEP = 0.001;
export const LAND = "twnDyh\\?pqAlE}A|Q_GdEgA~Cc@|F_@pDTbFLjGErFYjHy@vMiEdLuF`HoEzGwFfKsGvBiCrK_K~J_KHK bxoDwPd@UV_@Em@_@_@k@Ui@G}Ab@e@^Qf@L\\`@^l@Xh@FVGX[ zipD{g@qAl@YzA`@|@vAc@Mi@LuA tirDsuAOPLPLQ?K zirDcvAGABF vurDufBKIKF?PL@ j|qDHCK_DyAg@g@MoAo@Ng@Ke@SaAQg@o@WGe@@SG_@\\WvAEP[RUtAiAhAi@@A?";
export const BORDERS = "b~nDeyY^aCC_AI_@g@s@oAo@o@uAw@g@ jdsDcl[g@Ec@k@k@uBi@kAG]@e@`@cB?y@VaA@i@IWi@o@U{@D{BGaAQQ";
