// Natural Earth 1:10m land and country borders, -120 to -105 longitude, -30 to -15 latitude (public domain). Generated by scripts/generate-world-map-data.ts; do not edit.
export const STEP = 0.001;
export const LAND = "~itEf|s@WXLZ`@Rz@Lb@R`BNt@d@rAPd@`@VBRKDM}@qDs@{@a@Q}ElAu@O f~lE`ur@TMOA";
export const BORDERS = "";
