// Natural Earth 1:10m land and country borders, -135 to -120 longitude, -30 to -15 latitude (public domain). Generated by scripts/generate-world-map-data.ts; do not edit.
export const STEP = 0.001;
export const LAND = "nc}Fv}o@e@G]Td@B bvrFpdo@TB_@CEN xtfGxcl@MAaAq@k@MrAlBf@I pj~Ffvm@G?@FPLBI rsyFfon@s@TY|@A~@R^h@Yh@y@N}@";
export const BORDERS = "";
