// Natural Earth 1:10m land and country borders, -165 to -150 longitude, -30 to -15 latitude (public domain). Generated by scripts/generate-world-map-data.ts; do not edit.
export const STEP = 0.001;
export const LAND = "lzfHbu_@[CcAVc@~@yB|C`Br@XF\\MH^LD`@Bf@YRcALuDG] |feHhoa@W[ETHV zskHzx_@[bAF?PYb@yAYH hjhHvb_@TLNGEI txlHt{]Ae@\\OWEKLEh@DJRF ttfHjxj@Q@STWl@LdBPJF?Fq@`@}A |msHjvi@[FURg@l@ETVNx@HZCd@YNWIWg@g@ v_sHlre@?rCZ\\?[b@o@BY z|eH`w_@GOO@QLKT@f@FPPCJTZDp@i@BSIY b~eHfs_@c@~@BJn@`@XDLo@e@_BKC fmgHzd_@_@KSVMrA^?Z[Le@ `grHtjf@H`@TLTEP]?c@SK]H zvsHr`f@Fd@\\Lb@G\\]Hq@]Em@P xkuHhsd@p@]JQSE[j@[E pawH|wc@WCUNANPUPd@Ep@LRTALQ@WGe@ byfHhn_@HxAxCkAGqAWWeBEJZy@@UZBT jbwHbkh@oAJ]RM\\?f@L`@|@Ed@QnADXUMOO{@OM tcmHjqi@CNJM jkuHtqd@GKSDIZJJ";
export const BORDERS = "";
