// Natural Earth 1:10m land and country borders, -165 to -150 longitude, 0 to 15 latitude (public domain). Generated by scripts/generate-world-map-data.ts; do not edit.
export const STEP = 0.001;
export const LAND = "~d|HyqK]??\\\\? l_rHgmBWRGf@F^\\Iz@Xj@EpAiAj@CjE{@jAc@|C{BPHR@d@O\\_@Ew@cAi@m@@EF\\NVZHb@Yb@gA?S^gADs@NNU|@c@LYm@HKO@a@SLY|@WHGOBYZm@BSKa@WNIEDe@UL@d@GPSJo@k@K]DQjBi@rAw@\\_@VIR`@TAPQ@[YQi@@eBXkAz@_Cb@WAHf@JL\\LFPNhCm@p@eA`@eCxA rhxHieHLO_@KUBUNFJVB xo{H}nJEHDPVFb@EDEe@UVB`@IaAA hbvHeqFeAlBDRRTzAZn@Af@YNg@c@A_BZSIBu@Xa@dA_@b@kAXCVF^b@u@`BtAk@GqAy@{@eAL]p@Mj@";
export const BORDERS = "";
