// Natural Earth 1:10m land and country borders, -165 to -150 longitude, -15 to 0 latitude (public domain). Generated by scripts/generate-world-map-data.ts; do not edit.
export const STEP = 0.001;
export const LAND = "hnsHhpPh@?`@Ix@m@IK{Bv@ rlyHzgSRS_@PsArA ~ryHdrRc@O`@b@ zpwHnVi@GDRXL ~ngHrfUo@tAEr@f@JTa@Nm@Ai@ tnoH`~Ie@O]JIRNHjAH^ITi@c@? fwmH|{FcB]k@?Lh@Vb@?VKVV?X_@XIf@YLS vldH`pRILHBLGAK fkdH|jRENLW bqsHrwPU^FA~@{A plsHjsPEJ^Y@O ~ssHfuP?DJGt@wA";
export const BORDERS = "";
