// Natural Earth 1:10m land and country borders, -180 to -165 longitude, -45 to -30 latitude (public domain). Generated by scripts/generate-world-map-data.ts; do not edit.
export const STEP = 0.001;
export const LAND = "``wInluA}@`@dA`@RXDj@pBn@A[X[GEFEg@sAp@m@WU]KmAG]DIH znwItvtADNLDLCHwAHSeAu@_@k@Ge@b@g@z@OlB?nBOj@JCl@e@VuD\\pCxAJXeAdAMXEjAo@XkAo@Y|A{@l@mARYn@x@LjCLfAXp@`@xAZLh@hC@d@ENODk@Le@l@kAl@[sDcBUOIWm@Ue@_@Jm@vAyBxA_At@KdARRGLLIZp@@\\Jx@UnC`@x@g@]e@oAUi@ULm@[IiAh@sDOg@Qm@}Ai@IqAZoB?eCn@q@F}L[?J^@TJLV?^pAc@pA^fA~@`BxBP^";
export const BORDERS = "";
