// Natural Earth 1:10m land and country borders, -180 to -165 longitude, 15 to 30 latitude (public domain). Generated by scripts/generate-world-map-data.ts; do not edit.
export const STEP = 0.001;
export const LAND = "rbjIov_@YCj@N xbgIqyo@J[EAGF tknIyiq@Jh@RGBY xwrIm|q@I^JG `jyIebv@OHZB zkyIkbv@ZVb@FW] bf{Icnv@CP^H vbjIyt_@S@f@RNACG vscIcrm@?FDE bkvIggu@BDBE";
export const BORDERS = "";
