// Natural Earth 1:10m land and country borders, -180 to -165 longitude, 0 to 15 latitude (public domain). Generated by scripts/generate-world-map-data.ts; do not edit.
export const STEP = 0.001;
export const LAND = "juwIiKQ?CFFD vswIcMALHE";
export const BORDERS = "";
